# Generated by Django 3.2.8 on 2024-08-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nyumbani_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
