FROM python:3.9
ENV PYTHONUNBUFFERED 1
ENV DEBUG 1
RUN apt-get update &&\
    apt-get install -y binutils libproj-dev gdal-bin
RUN mkdir /app
WORKDIR /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY . /app
