version: '3'

services:
  pg:
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    image: mdillon/postgis:10
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pg
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=pg
      - DATABASE_URL=postgis://postgres:postgres@pg:5432/postgres
      - PORT=8000

volumes:
  pgdata:

