version: '3'

services:
  pg:
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    image: postgres:15-alpine3.20
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pg
    stdin_open: true
    tty: true
    env_file:
      - .env

volumes:
  pgdata:

