# Generated by Django 3.2.8 on 2024-07-25 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_userorganization_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userorganization',
            unique_together={('user', 'organization')},
        ),
    ]
