# Generated by Django 3.2.8 on 2024-07-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_userorganization_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganization',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
