# Generated by Django 3.2.8 on 2024-09-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_userorganization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='nyumbani_organization_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
