# Generated by Django 3.2.8 on 2024-07-30 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_userorganization_unique_together'),
        ('bookings', '0004_alter_booking_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('organization', 'name', 'building')},
        ),
    ]
