# Generated by Django 3.2.8 on 2024-07-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_active_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active_menu', True)), fields=('id', 'organization'), name='unique_active_menu_per_organization'),
        ),
    ]
